# Generated by Django 5.1.4 on 2025-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='forum_post_author__76a783_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='forum_post_is_pinn_6894f6_idx'),
        ),
    ]
