# Generated by Django 5.1.4 on 2025-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_options_booking_move_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
